export type ProjectCategory = "artes" | "capas" | "logos" | "videos" | "sites"

export interface Project {
  slug: string
  title: string
  category: ProjectCategory
  categoryLabel: string
  client: string
  rating: number
  testimonial: string
  team: string
  teamRole: string
  image: string
  description: string
  videoUrl?: string
  siteUrl?: string
}

export const projects: Project[] = [
  // Artes
  // Boi Feliz - Nutrição Animal
  {
    slug: "boi-feliz-deficiencias",
    title: "Boi Feliz - Deficiências",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Boi Feliz",
    rating: 5.0,
    testimonial: "Campanha educacional que aumentou o reconhecimento da marca no agronegócio.",
    team: "Equipe Arfen",
    teamRole: "Marketing Agro & Design",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/6-CQ0dQaVpvEQqQfDweFu0s9pKcvgU9n.jpeg",
    description: "Arte educativa sobre sinais de alerta em bovinos: pelo arrepiado e perda de peso. Destaca prevenção com alimentação, água limpa, vacinação, controle de pragas e espaço limpo.",
  },
  {
    slug: "boi-feliz-seguranca",
    title: "Boi Feliz - Segurança",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Boi Feliz",
    rating: 5.0,
    testimonial: "Design premium que transmitiu confiança e profissionalismo no mercado pecuário.",
    team: "Equipe Arfen",
    teamRole: "Fotografia de Produto & Branding",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/14-rQQ3K6yPE00aVZQTbIDAKoA1ropLl9.png",
    description: "Campanha institucional destacando segurança e confiança. Mostra produtor com produtos Boi Feliz, enfatizando registro MAPA e garantia de saúde e rendimento do rebanho.",
  },
  {
    slug: "boi-feliz-revolucao",
    title: "Boi Feliz - Revolução no Cocho",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Boi Feliz",
    rating: 5.0,
    testimonial: "Arte impactante que gerou forte engajamento e debate sobre produtividade pecuária.",
    team: "Equipe Arfen",
    teamRole: "Design Conceitual & Marketing",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1-3XJZkwwnmpHjOeZpL81OT6vjVSxo18.png",
    description: "Arte dramática com touro e cortes de carne empilhados. Mensagem provocativa sobre lucro na pecuária e revolução no rendimento do pasto com Boi Feliz.",
  },
  {
    slug: "boi-feliz-bezerros",
    title: "Boi Feliz - Uso em Bezerros",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Boi Feliz",
    rating: 5.0,
    testimonial: "Conteúdo educacional que esclareceu dúvidas frequentes dos pecuaristas.",
    team: "Equipe Arfen",
    teamRole: "Marketing Educacional",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/21-xSwLimHrILiXnKih45fcHVuTFhMd6r.png",
    description: "Arte respondendo dúvida comum: pode usar em bezerros? Sim, indicado para todas as idades. Começar cedo garante adultos muito mais produtivos. Mostra diferentes raças bovinas.",
  },
  {
    slug: "boi-feliz-diferencial-tecnico",
    title: "Boi Feliz - Diferencial Técnico",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Boi Feliz",
    rating: 5.0,
    testimonial: "Design sofisticado que valorizou o diferencial científico do produto.",
    team: "Equipe Arfen",
    teamRole: "Branding Técnico & Marketing",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/11-NJ5IaZLipiaIkqBL4r7xjaV9GPlgrp.png",
    description: "Arte institucional sobre o poder da sinergia entre minerais e vitaminas. Não é apenas mistura, é ciência. Cada componente escolhido para potencializar o ganho de peso.",
  },
  {
    slug: "deyse-limma-retro",
    title: "Deyse Limma - Viagem no Tempo",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Deyse Limma",
    rating: 5.0,
    testimonial: "Arte elegante que capturou perfeitamente a essência retrô do evento musical.",
    team: "Equipe Arfen",
    teamRole: "Design Musical & Branding de Artista",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-1770747240192-bRUCofWuDH1t8Srw8DqEHHAj1JoUOU.png",
    description: "Arte promocional retrô para evento musical. Destaca a artista Deyse Limma em cenário vintage com iluminação neon e atmosfera de bar clássico, transmitindo elegância nostálgica.",
  },
  {
    slug: "iskerda-artilheiro",
    title: "Iskerda - Artilheiro",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Iskerda Futebol",
    rating: 5.0,
    testimonial: "Design impactante que celebrou conquistas esportivas com identidade visual marcante.",
    team: "Equipe Arfen",
    teamRole: "Design Esportivo & Branding",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/8-50jdWjGM5pxGJghBUNrQJBOlK4K8O8.png",
    description: "Arte esportiva celebrando jogador artilheiro. Apresenta atleta com coroa dourada, uniforme Nike preto, bola e chuteira em ouro. Design premium com tema de campeão e realeza.",
  },
  {
    slug: "investelab-treinamento",
    title: "InvesteLab - Treinamento Financeiro",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "InvesteLab",
    rating: 5.0,
    testimonial: "Design profissional que transmitiu credibilidade e autoridade no mercado financeiro.",
    team: "Equipe Arfen",
    teamRole: "Marketing Digital & Branding Financeiro",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-02-10%20at%2015.22.46-2OqMWQTBmRIOsw0RV5LXZGvUsVQ1PP.jpeg",
    description: "Campanha de marketing para treinamento de investimentos. Arte em preto e branco com profissional confiante, convidando a conhecer alternativas ao CDB com call-to-action direto.",
  },
  {
    slug: "heineken-bottle",
    title: "Heineken",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Heineken",
    rating: 5.0,
    testimonial: "Fotografia de produto profissional com identidade visual premium da marca.",
    team: "Equipe Arfen",
    teamRole: "Fotografia de Produto & Branding",
    image: "/arts/heineken.png",
    description: "Campanha visual completa para redes sociais com foco em engajamento e conversão.",
  },
  {
    slug: "starbucks-frappuccino",
    title: "Starbucks",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Starbucks",
    rating: 5.0,
    testimonial: "Design impactante que elevou nossa campanha a um novo patamar de resultados.",
    team: "Equipe Arfen",
    teamRole: "Design & Marketing Visual",
    image: "/arts/starbucks.png",
    description: "Criação de artes promocionais para lançamento de nova linha de produtos.",
  },
  {
    slug: "mango-energy-drink",
    title: "Mango Energy",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Mango",
    rating: 5.0,
    testimonial: "Conteúdo visual estratégico que dobrou nosso engajamento nas redes sociais.",
    team: "Equipe Arfen",
    teamRole: "Social Media & Design",
    image: "/arts/mango-energy.png",
    description: "Série de posts em carrossel otimizados para maximizar alcance orgânico.",
  },
  {
    slug: "gardens-fusion-carnival-1",
    title: "Garden's Fusion",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Garden's Fusion",
    rating: 5.0,
    testimonial: "Identidade visual moderna que reflete perfeitamente os valores da nossa marca.",
    team: "Equipe Arfen",
    teamRole: "Branding & Social Design",
    image: "/arts/carnival-gardens1.png",
    description: "Stories interativos com design minimalista e alta taxa de conversão.",
  },
  {
    slug: "carnaval-green-theme",
    title: "Carnaval",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Evento Carnaval",
    rating: 5.0,
    testimonial: "Arte vibrante que capturou a energia e alegria do carnaval.",
    team: "Equipe Arfen",
    teamRole: "Design de Eventos",
    image: "/arts/carnaval-green.png",
    description: "Campanha completa para evento de carnaval com identidade visual única.",
  },
  {
    slug: "gardens-fusion-orange",
    title: "Garden's Fusion",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Garden's Fusion",
    rating: 5.0,
    testimonial: "Design profissional que elevou a percepção do evento.",
    team: "Equipe Arfen",
    teamRole: "Design de Eventos",
    image: "/arts/gardens-fusion-orange.png",
    description: "Material promocional completo para evento de aniversário.",
  },
  {
    slug: "design-vr-arfen",
    title: "Design VR",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Arfen",
    rating: 5.0,
    testimonial: "Comunicação moderna e impactante sobre o valor do design.",
    team: "Equipe Arfen",
    teamRole: "Branding & Marketing",
    image: "/arts/design-vr.png",
    description: "Campanha institucional sobre a importância do design profissional.",
  },
  {
    slug: "gardens-coffee-event",
    title: "Garden's Fusion Coffee",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Garden's Fusion",
    rating: 5.0,
    testimonial: "Arte elegante e sofisticada para evento especial.",
    team: "Equipe Arfen",
    teamRole: "Design de Eventos",
    image: "/arts/gardens-coffee.png",
    description: "Material visual premium para evento temático de carnaval.",
  },
  {
    slug: "velve-tools-specifications",
    title: "Velve Tools",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Velve",
    rating: 5.0,
    testimonial: "Material técnico com design profissional e informativo.",
    team: "Equipe Arfen",
    teamRole: "Design Industrial",
    image: "/arts/velve-tools.webp",
    description: "Especificações técnicas com identidade visual industrial.",
  },
  {
    slug: "barber-shop-regua",
    title: "Barbearia",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Barbearia",
    rating: 5.0,
    testimonial: "Design ousado que impulsionou agendamentos no fim de semana.",
    team: "Equipe Arfen",
    teamRole: "Marketing Local",
    image: "/arts/barber-regua.png",
    description: "Campanha promocional para barbearia com call-to-action direto.",
  },
  {
    slug: "votoran-construction",
    title: "Votoran",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Ingolide Construction",
    rating: 5.0,
    testimonial: "Campanha promocional que aumentou significativamente as vendas do cimento Votoran.",
    team: "Equipe Arfen",
    teamRole: "Marketing & Design",
    image: "/arts/votoran-cement.webp",
    description: "Arte promocional para materiais de construção com 25% de desconto.",
  },
  {
    slug: "micropigmentation-beauty",
    title: "Micropigmentação",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Estúdio de Beleza",
    rating: 5.0,
    testimonial: "Design elegante que transmite profissionalismo e cuidado no serviço de beleza.",
    team: "Equipe Arfen",
    teamRole: "Branding de Beleza",
    image: "/arts/micropigmentation.webp",
    description: "Conteúdo educativo sobre micropigmentação com identidade visual sofisticada.",
  },
  {
    slug: "apple-watch-series2",
    title: "Apple Watch",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Phone Store",
    rating: 5.0,
    testimonial: "Arte promocional moderna que destacou os recursos do Apple Watch Series 2.",
    team: "Equipe Arfen",
    teamRole: "Design de Produto",
    image: "/arts/apple-watch.jpg",
    description: "Campanha para loja de tecnologia destacando smartwatch e suas funcionalidades.",
  },
  {
    slug: "nativa-spa-hair",
    title: "Nativa SPA",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "O Boticário",
    rating: 5.0,
    testimonial: "Design delicado que valorizou o produto e aumentou as conversões.",
    team: "Equipe Arfen",
    teamRole: "Branding de Cosméticos",
    image: "/arts/nativa-spa.webp",
    description: "Promoção de produtos capilares com estética clean e feminina.",
  },
  {
    slug: "beauty-eyebrow-message",
    title: "Autoestima",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Estúdio de Beleza",
    rating: 5.0,
    testimonial: "Mensagem inspiradora que conectou emocionalmente com nosso público.",
    team: "Equipe Arfen",
    teamRole: "Branding Emocional",
    image: "/arts/beauty-eyebrow-quote.webp",
    description: "Conteúdo sobre autoestima e cuidado pessoal com design sofisticado.",
  },
  {
    slug: "scandal-perfume-promo",
    title: "Scandal",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Perfumaria",
    rating: 5.0,
    testimonial: "Arte promocional elegante que impulsionou vendas do perfume Scandal.",
    team: "Equipe Arfen",
    teamRole: "Marketing de Luxo",
    image: "/arts/scandal-perfume.webp",
    description: "Campanha de descontos com identidade visual premium e feminina.",
  },
  {
    slug: "skincare-routine",
    title: "Skincare",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Estúdio de Beleza",
    rating: 5.0,
    testimonial: "Comunicação visual que educou e converteu clientes em tratamentos faciais.",
    team: "Equipe Arfen",
    teamRole: "Marketing de Beleza",
    image: "/arts/skincare-serum.webp",
    description: "Conteúdo sobre cuidados com a pele com fotografia profissional.",
  },
  {
    slug: "nail-art-promotion",
    title: "Manicure",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Salão de Beleza",
    rating: 5.0,
    testimonial: "Design vibrante que triplicou agendamentos de manicure.",
    team: "Equipe Arfen",
    teamRole: "Marketing Local",
    image: "/arts/nail-art-stress.webp",
    description: "Campanha promocional de nail art com tema Valentine's Day.",
  },
  {
    slug: "spiderman-carousel-fonts",
    title: "Spider-Man Fonts",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Design Educacional",
    rating: 5.0,
    testimonial: "Material educativo sobre tipografia que viralizou nas redes sociais.",
    team: "Equipe Arfen",
    teamRole: "Design & Educação",
    image: "/arts/spiderman-carousel.jpg",
    description: "Carrossel sobre combinações perfeitas de fontes com tema Spider-Man.",
  },
  {
    slug: "versace-eros-perfume",
    title: "Versace Eros",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Perfumaria de Luxo",
    rating: 5.0,
    testimonial: "Campanha premium que valorizou o perfume Versace Eros.",
    team: "Equipe Arfen",
    teamRole: "Marketing de Luxo",
    image: "/arts/versace-eros.webp",
    description: "Promoção de fragrância masculina com fotografia de produto premium.",
  },
  {
    slug: "feed-overlay-tutorial",
    title: "Feed Overlay",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Tutorial Photoshop",
    rating: 5.0,
    testimonial: "Conteúdo educacional que ensinou técnicas avançadas de design.",
    team: "Equipe Arfen",
    teamRole: "Design Educacional",
    image: "/arts/feed-overlay-effect.jpg",
    description: "Tutorial sobre efeitos de sobreposição no Photoshop com design minimalista.",
  },
  {
    slug: "airpods-max-sound-perfection",
    title: "AirPods Max",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Gadgets",
    rating: 5.0,
    testimonial: "Design premium que destacou perfeitamente os diferenciais do produto.",
    team: "Equipe Arfen",
    teamRole: "Design de Produto Tech",
    image: "/arts/airpods-max-gadgets.jpg",
    description: "Campanha promocional para fones premium com foco em qualidade sonora.",
  },
  {
    slug: "easter-chocolate-campaign",
    title: "Páscoa Feliz",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Confeitaria",
    rating: 5.0,
    testimonial: "Arte criativa e deliciosa que aumentou vendas de Páscoa em 200%.",
    team: "Equipe Arfen",
    teamRole: "Marketing Sazonal",
    image: "/arts/easter-chocolate.jpg",
    description: "Campanha de Páscoa com ovo de chocolate e coelho, design criativo e vibrante.",
  },
  {
    slug: "porsche-911-gt3-showcase",
    title: "Porsche 911 GT3 RS",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "O Grego Concessionária",
    rating: 5.0,
    testimonial: "Fotografia automotiva de altíssimo nível que vendeu o carro em 48h.",
    team: "Equipe Arfen",
    teamRole: "Fotografia Automotiva",
    image: "/arts/porsche-911-gt3.jpg",
    description: "Showcase premium do Porsche 911 GT3 RS com ficha técnica completa.",
  },
  {
    slug: "mercedes-amg-cle-launch",
    title: "Mercedes-AMG CLE",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Mercedes-Benz",
    rating: 5.0,
    testimonial: "Campanha de lançamento que gerou 500+ leads qualificados.",
    team: "Equipe Arfen",
    teamRole: "Marketing Automotivo",
    image: "/arts/mercedes-amg-cle.jpg",
    description: "Lançamento do Mercedes-AMG CLE com fotografia de estúdio premium.",
  },
  {
    slug: "ferrari-niki-lauda-tribute",
    title: "Niki Lauda Tribute",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Ferrari Heritage",
    rating: 5.0,
    testimonial: "Homenagem emocionante que viralizou entre fãs de F1 no mundo todo.",
    team: "Equipe Arfen",
    teamRole: "Design de Tributo",
    image: "/arts/ferrari-niki-lauda.jpg",
    description: "Tributo ao tricampeão Niki Lauda com Ferrari 312 T2 de 1976.",
  },
  {
    slug: "sprite-fresh-campaign",
    title: "Fresh Sprite",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Coca-Cola Company",
    rating: 5.0,
    testimonial: "Campanha refrescante que aumentou vendas de Sprite em 45%.",
    team: "Equipe Arfen",
    teamRole: "Marketing de Bebidas",
    image: "/arts/sprite-fresh.jpg",
    description: "Promoção de Sprite com fotografia de produto e elementos frescos.",
  },
  {
    slug: "smartwatch-product-template",
    title: "Smartwatch Template",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Template Educacional",
    rating: 5.0,
    testimonial: "Template profissional usado por centenas de designers.",
    team: "Equipe Arfen",
    teamRole: "Design de Templates",
    image: "/arts/smartwatch-example.jpg",
    description: "Template exemplo para relógio inteligente com especificações técnicas.",
  },
  {
    slug: "healthy-lifestyle-post",
    title: "Vida Saudável",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Nutricionista",
    rating: 5.0,
    testimonial: "Post inspirador que gerou 10k+ curtidas e 500+ compartilhamentos.",
    team: "Equipe Arfen",
    teamRole: "Marketing de Saúde",
    image: "/arts/healthy-salad.jpg",
    description: "Campanha motivacional sobre estilo de vida saudável com salada fresca.",
  },
  {
    slug: "luxury-watches-lange",
    title: "Relógios de Luxo",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "A. Lange & Söhne",
    rating: 5.0,
    testimonial: "Campanha premium que aumentou tráfego no site em 150%.",
    team: "Equipe Arfen",
    teamRole: "Marketing de Luxo",
    image: "/arts/luxury-watches.png",
    description: "Arte promocional sofisticada para relógios de alta relojoaria com call-to-action.",
  },
  {
    slug: "porsche-911-editorial",
    title: "Porsche 911",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Porsche Brasil",
    rating: 5.0,
    testimonial: "Material editorial completo que celebrou a história do icônico 911 GT3 RS.",
    team: "Equipe Arfen",
    teamRole: "Design Editorial Automotivo",
    image: "/arts/porsche-911-poster.jpg",
    description: "Poster informativo em português sobre o Porsche 911 GT3 RS com ficha técnica.",
  },
  {
    slug: "nike-jordan-wairwalk",
    title: "Air Jordan 4",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Nike",
    rating: 5.0,
    testimonial: "Campanha de sneakers que viralizou entre sneakerheads e gerou fila virtual.",
    team: "Equipe Arfen",
    teamRole: "Marketing Streetwear",
    image: "/arts/nike-jordan-yellow.jpg",
    description: "Arte promocional vibrante para Air Jordan 4 amarelo com tipografia ousada.",
  },
  {
    slug: "iphone-17-concept",
    title: "iPhone 17 Concept",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Apple Concept",
    rating: 5.0,
    testimonial: "Design minimalista futurista que ganhou destaque em portais de tecnologia.",
    team: "Equipe Arfen",
    teamRole: "Design de Produto Tech",
    image: "/arts/iphone-17-2025.png",
    description: "Arte conceitual minimalista do iPhone 17 para 2025 em preto e branco.",
  },
  {
    slug: "lime-export-fertiquimica",
    title: "Limão Exportação",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "FertiQuímica",
    rating: 5.0,
    testimonial: "Campanha B2B que posicionou nosso protocolo como referência no agronegócio.",
    team: "Equipe Arfen",
    teamRole: "Marketing Agro",
    image: "/arts/lime-export-fertiquimica.webp",
    description: "Protocolo FertiQuímica para limão padrão exportação com fotografia profissional.",
  },
  {
    slug: "arcaneec-premium-hoodie",
    title: "Premium Hoodie",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Arcaneec",
    rating: 5.0,
    testimonial: "Mockup profissional que ajudou a vender 500+ unidades em pré-venda.",
    team: "Equipe Arfen",
    teamRole: "E-commerce Design",
    image: "/arts/arcaneec-hoodie.png",
    description: "Template de produto para moletom premium verde com opções de tamanho e cor.",
  },
  {
    slug: "hair-salon-secret",
    title: "Hair Care Secret",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Salão de Beleza",
    rating: 5.0,
    testimonial: "Post que gerou 2000+ salvamentos e se tornou referência em cuidados capilares.",
    team: "Equipe Arfen",
    teamRole: "Marketing de Beleza",
    image: "/arts/hair-care-secret.png",
    description: "Conteúdo educacional sobre cuidados com fios danificados e tratamentos capilares.",
  },
  {
    slug: "design-trends-2025",
    title: "Design Trends 2025",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Design Community",
    rating: 5.0,
    testimonial: "Post viral sobre tendências de design que alcançou 50k+ designers.",
    team: "Equipe Arfen",
    teamRole: "Design Educacional",
    image: "/arts/design-trends-2025.png",
    description: "Arte criativa sobre tendências de design 2025 com estátua grega moderna.",
  },
  {
    slug: "natura-ekos-andiroba",
    title: "Natura Ekos",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Natura",
    rating: 5.0,
    testimonial: "Design limpo e sustentável que valorizou a linha Ekos Andiroba.",
    team: "Equipe Arfen",
    teamRole: "Branding Sustentável",
    image: "/arts/natura-ekos-andiroba.png",
    description: "Polpa descolorante hidratante para o corpo com óleo de andiroba da Amazônia.",
  },
  {
    slug: "tennessee-wrigth-milestone",
    title: "Tennessee Football",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "University of Tennessee",
    rating: 5.0,
    testimonial: "Arte comemorativa que celebrou marco histórico do atleta Jaynen Wrigth.",
    team: "Equipe Arfen",
    teamRole: "Sports Design",
    image: "/arts/tennessee-wrigth.jpg",
    description: "Comemoração de 1000+ jardas corridas de Jaynen Wrigth na temporada 2023.",
  },
  {
    slug: "chess-positioning-strategy",
    title: "Estratégia de Posicionamento",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Consultoria Estratégica",
    rating: 5.0,
    testimonial: "Post inspirador que gerou reflexão profunda sobre posicionamento de marca.",
    team: "Equipe Arfen",
    teamRole: "Branding Estratégico",
    image: "/arts/chess-positioning-strategy.jpg",
    description: "Arte conceitual com xadrez sobre a importância do posicionamento estratégico.",
  },
  {
    slug: "megaclick-conversion-system",
    title: "MegaClick",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "MegaClick",
    rating: 5.0,
    testimonial: "Campanha impactante que converteu 200+ leads qualificados em 48h.",
    team: "Equipe Arfen",
    teamRole: "Marketing SaaS",
    image: "/arts/megaclick-strategy.png",
    description: "Sistema inteligente de conversão e vendas para e-commerce com foco em estratégia.",
  },
  {
    slug: "marketplace-visibility-crisis",
    title: "Visibilidade Marketplace",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "SaaS Posicionamento",
    rating: 5.0,
    testimonial: "Arte dramática que traduziu perfeitamente a dor do cliente invisível.",
    team: "Equipe Arfen",
    teamRole: "Marketing SaaS B2B",
    image: "/arts/marketplace-visibility-saas.png",
    description: "SaaS de posicionamento em marketplace com mensagem urgente sobre visibilidade.",
  },
  {
    slug: "ai-business-workshop",
    title: "Workshop IA",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Os Fora da Caixa",
    rating: 5.0,
    testimonial: "Material que esgotou ingressos do workshop em menos de 72 horas.",
    team: "Equipe Arfen",
    teamRole: "Design de Eventos",
    image: "/arts/ai-workshop-campinas.png",
    description: "Workshop sobre Inteligência Artificial para Negócios em Campinas com Pedro Gadelha e Ana Tex.",
  },
  {
    slug: "gardens-fusion-carnaval-gold",
    title: "Garden's Fusion Gold",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Garden's Fusion",
    rating: 5.0,
    testimonial: "Identidade visual luxuosa que posicionou o evento como premium no mercado.",
    team: "Equipe Arfen",
    teamRole: "Design de Eventos Premium",
    image: "/arts/gardens-fusion-carnaval-luxury.png",
    description: "Edição Carnaval com tema dourado luxuoso incluindo ampulheta, violino e grãos de café.",
  },
  {
    slug: "sj-jaqueline-spotify-promo",
    title: "SJ Jaqueline Spotify",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "SJ Jaqueline",
    rating: 5.0,
    testimonial: "Campanha que aumentou seguidores no Spotify em 300% em uma semana.",
    team: "Equipe Arfen",
    teamRole: "Marketing Musical",
    image: "/arts/sj-jaqueline-spotify.png",
    description: "Promoção de artista no Spotify com player interface e música Canetaria.",
  },
  {
    slug: "stay-updated-design-3d",
    title: "Esteja Sempre Atualizado",
    category: "artes",
    categoryLabel: "Arte Gráfica",
    client: "Comunidade Design",
    rating: 5.0,
    testimonial: "Post viral que inspirou milhares de designers a se manterem atualizados.",
    team: "Equipe Arfen",
    teamRole: "Design 3D & Motion",
    image: "/arts/stay-updated-design.png",
    description: "Arte 3D motivacional estilo Pixar sobre a importância de estar sempre atualizado no design.",
  },

  // Capas
  {
    slug: "quando-ia-nao-era-humana",
    title: "Quando a IA Não Era Humana",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Rud Gregório",
    rating: 5.0,
    testimonial: "Capa impactante que viralizou nas redes e triplicou as vendas do livro.",
    team: "Equipe Arfen",
    teamRole: "Design Editorial & Conceito",
    image: "/covers/ai-nao-era-humana.png",
    description: "Capa dramática sobre IA com robô marionete controlado por mãos humanas, tipografia azul em caixa alta.",
  },
  {
    slug: "transformar-erros-dinheiro",
    title: "Como Transformar Erros",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Antônio Aguiar",
    rating: 5.0,
    testimonial: "Design conceitual que transmite perfeitamente a mensagem de superação.",
    team: "Equipe Arfen",
    teamRole: "Design Editorial & Ilustração",
    image: "/covers/transformar-erros.webp",
    description: "Capa motivacional com chave-ponte sobre abismo, sobre transformar erros em dinheiro e sabedoria.",
  },
  {
    slug: "homem-nao-substituido",
    title: "O Homem Não Substituído",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Rud Gregório",
    rating: 5.0,
    testimonial: "Minimalismo elegante que captura a essência da relevância humana na era digital.",
    team: "Equipe Arfen",
    teamRole: "Design Minimalista",
    image: "/covers/homem-nao-substituido.png",
    description: "Capa minimalista com aperto de mãos robóticas, sobre manter relevância na era da automação.",
  },
  {
    slug: "leida-grana",
    title: "A Leida Grana",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Rud Gregório",
    rating: 5.0,
    testimonial: "Design vibrante e chamativo que aumentou o interesse do público em 250%.",
    team: "Equipe Arfen",
    teamRole: "Design Editorial Financeiro",
    image: "/covers/leida-grana.png",
    description: "Capa sobre educação financeira com saco de dinheiro e moedas douradas, por que dinheiro não aceita desaforo.",
  },
  {
    slug: "autoconfianca-inabalavel",
    title: "Autoconfiança Inabalável",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Camili Gregório",
    rating: 5.0,
    testimonial: "Arte emocional poderosa que conectou profundamente com o público-alvo feminino.",
    team: "Equipe Arfen",
    teamRole: "Design Emocional & Fotografia",
    image: "/covers/autoconfianca-inabalavel.png",
    description: "Capa artística de autoajuda com fotografia de retrato feminino e efeitos de luz vermelha, sobre parar de duvidar de si.",
  },
  {
    slug: "arte-charme-natural",
    title: "A Arte do Charme Natural",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Camili Gregório",
    rating: 5.0,
    testimonial: "Capa glamourosa que capturou perfeitamente a essência da elegância feminina.",
    team: "Equipe Arfen",
    teamRole: "Fotografia Editorial & Design",
    image: "/covers/arte-charme-natural.png",
    description: "Capa sofisticada com retrato feminino elegante em vermelho sobre fundo escuro, sobre conquistar respeito e admiração sem esforço.",
  },
  {
    slug: "lider-bastidores",
    title: "O Líder dos Bastidores",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Rud Gregório",
    rating: 5.0,
    testimonial: "Design surrealista único que se destacou nas prateleiras e gerou buzz nas redes.",
    team: "Equipe Arfen",
    teamRole: "Design Conceitual",
    image: "/covers/lider-bastidores.png",
    description: "Capa surrealista com homem de terno e chapéu coco com cabeça de nuvens, sobre o poder de quem comanda sem precisar aparecer.",
  },
  {
    slug: "ia-codigo-humano",
    title: "A IA do Código Humano",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Rud Gregório",
    rating: 5.0,
    testimonial: "Design tech futurista que posicionou o livro como referência em IA.",
    team: "Equipe Arfen",
    teamRole: "Design Tech & Futurista",
    image: "/covers/ia-codigo-humano.png",
    description: "Capa tecnológica com olho de IA feito de circuitos e código binário, sobre se reinventar antes da revolução.",
  },
  {
    slug: "seja-a-chefe",
    title: "Seja a Chefe",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Camili Gregório",
    rating: 5.0,
    testimonial: "Fotografia profissional impecável que inspirou milhares de mulheres empreendedoras.",
    team: "Equipe Arfen",
    teamRole: "Fotografia Corporativa",
    image: "/covers/seja-a-chefe.png",
    description: "Capa executiva com mulher de blazer vermelho em ambiente corporativo, sobre ter o que você gostaria de ter.",
  },
  {
    slug: "fim-programacao",
    title: "O Fim da Programação",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Tech Publisher",
    rating: 5.0,
    testimonial: "Arte distópica impactante que viralizou entre desenvolvedores e profissionais de tech.",
    team: "Equipe Arfen",
    teamRole: "Design Distópico & Glitch",
    image: "/covers/fim-programacao.png",
    description: "Capa distópica com ciborgue marionete controlado por cordas, efeitos glitch vermelhos e elementos de código.",
  },
  {
    slug: "dormir-bonita-acordar-invencivel",
    title: "Dormir Bonita, Acordar Invencível",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Camili Gregório",
    rating: 5.0,
    testimonial: "Design etéreo e calmante que ressoou profundamente com o público sobre bem-estar.",
    team: "Equipe Arfen",
    teamRole: "Design Atmosférico & Fotografia",
    image: "/covers/dormir-bonita-acordar-invencivel.png",
    description: "Capa contemplativa com silhueta feminina ao luar, tipografia serifada elegante em tons creme, sobre como o sono muda tudo.",
  },
  {
    slug: "30-dias-sem-reclamar",
    title: "30 Dias Sem Reclamar",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Camili Gregório",
    rating: 5.0,
    testimonial: "Design motivacional vibrante que gerou engajamento massivo e milhares de participantes no desafio.",
    team: "Equipe Arfen",
    teamRole: "Design Motivacional & Ilustração",
    image: "/covers/30-dias-sem-reclamar.png",
    description: "Capa energética com tipografia bold laranja e branca, cabeça ilustrada com cérebro luminoso, sobre o desafio que transforma corpo e mente.",
  },
  {
    slug: "cara-nao-precisava-provar",
    title: "O Cara Que Não Precisava Provar Nada",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Rud Gregório",
    rating: 5.0,
    testimonial: "Design masculino poderoso que se tornou referência em livros sobre confiança silenciosa.",
    team: "Equipe Arfen",
    teamRole: "Design Masculino & Fotografia",
    image: "/covers/cara-nao-precisava-provar.png",
    description: "Capa dramática com silhueta masculina executiva e peças de xadrez, tipografia impactante sobre confiança silenciosa.",
  },
  {
    slug: "peso-do-desejo",
    title: "O Peso do Desejo",
    category: "capas",
    categoryLabel: "Design Editorial",
    client: "Editora Literária",
    rating: 5.0,
    testimonial: "Fotografia artística que capturou perfeitamente a essência emocional da narrativa.",
    team: "Equipe Arfen",
    teamRole: "Fotografia Editorial & Design",
    image: "/covers/peso-do-desejo.png",
    description: "Capa contemplativa com silhueta em estrada rural ao entardecer, tons sépia quentes, sobre quando o destino decide morder.",
  },

  // Logos
  {
    slug: "luciano-multimidias-logo",
    title: "Luciano Multimídias",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Luciano Multimídias",
    rating: 5.0,
    testimonial: "Logo vibrante que transmite perfeitamente a essência criativa da nossa produtora.",
    team: "Equipe Arfen",
    teamRole: "Branding Multimídia",
    image: "/logos/luciano-multimidias.webp",
    description: "Logotipo criativo com símbolo infinito em gradiente arco-íris e ícones de produção audiovisual.",
  },
  {
    slug: "projeto-delta-federal-logo",
    title: "Projeto Delta Federal",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Delta Federal",
    rating: 5.0,
    testimonial: "Design poderoso que elevou nossa presença institucional e gerou reconhecimento imediato.",
    team: "Equipe Arfen",
    teamRole: "Branding Institucional",
    image: "/logos/projeto-delta-federal.webp",
    description: "Logo corporativo com águia laranja e tipografia bold preta transmitindo força e liderança.",
  },
  {
    slug: "henrique-lima-music-logo",
    title: "Henrique Lima Music",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Henrique Lima",
    rating: 5.0,
    testimonial: "Badge perfeito que captura a essência da minha música e virou marca registrada.",
    team: "Equipe Arfen",
    teamRole: "Branding Musical",
    image: "/logos/henrique-lima-music.webp",
    description: "Logo circular em preto e branco estilo badge com iniciais HL, guitarra e padrão de notas musicais.",
  },
  {
    slug: "pavertec-construcao-logo",
    title: "Pavertec Construções",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Pavertec",
    rating: 5.0,
    testimonial: "Identidade sólida que reflete nossos valores de base e construção perfeita.",
    team: "Equipe Arfen",
    teamRole: "Branding Corporativo",
    image: "/logos/pavertec-construcao.webp",
    description: "Logo arquitetônico com pilares geométricos em tons de azul e tagline sobre base para construção sólida.",
  },
  {
    slug: "acai-delirio-logo",
    title: "Açaí Delírio",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Açaí Delírio",
    rating: 5.0,
    testimonial: "Branding divertido e vibrante que triplicou nosso reconhecimento de marca nas redes.",
    team: "Equipe Arfen",
    teamRole: "Branding Food & Beverage",
    image: "/logos/acai-delirio.webp",
    description: "Logo descontraído com ilustração de açaí roxo e sorvete azul em gradiente vibrante azul-rosa.",
  },
  {
    slug: "lg-tabacaria-logo",
    title: "LG Tabacaria",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "LG Tabacaria",
    rating: 5.0,
    testimonial: "Design sofisticado que elevou nossa marca no mercado de produtos premium.",
    team: "Equipe Arfen",
    teamRole: "Branding Premium",
    image: "/logos/lg-tabacaria.webp",
    description: "Logo moderno com letras LG em gradiente colorido sobre fundo preto dramático com fumaça e produtos.",
  },
  {
    slug: "mario-odonto-logo",
    title: "Mario Odonto",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Dr. Mario Odontologia",
    rating: 5.0,
    testimonial: "Logo memorável que trouxe personalidade e confiança para nossa clínica.",
    team: "Equipe Arfen",
    teamRole: "Branding Saúde",
    image: "/logos/mario-odonto.webp",
    description: "Logo odontológico criativo com dente 3D usando chapéu estilizado em fundo azul céu.",
  },
  {
    slug: "dell-pratas-logo",
    title: "Dell Pratas",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Dell Pratas",
    rating: 5.0,
    testimonial: "Identidade luxuosa que posicionou nossa joalheria como referência premium.",
    team: "Equipe Arfen",
    teamRole: "Branding Luxo",
    image: "/logos/dell-pratas.webp",
    description: "Logo elegante com ilustração 3D de rubi e tipografia dourada sobre fundo ornamental vermelho escuro.",
  },
  {
    slug: "tonton-tete-kids-logo",
    title: "Tonton Tetê Fashion Kids",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Tonton Tetê",
    rating: 5.0,
    testimonial: "Branding encantador que conquistou crianças e pais, aumentando vendas em 180%.",
    team: "Equipe Arfen",
    teamRole: "Branding Infantil",
    image: "/logos/tonton-tete-kids.webp",
    description: "Logo infantil fofo com nuvem 3D, estrela kawaii, arco-íris e corações em gradiente roxo-laranja.",
  },
  {
    slug: "expansao-midia-logo",
    title: "Expansão de Mídia",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Expansão de Mídia",
    rating: 5.0,
    testimonial: "Design moderno que comunica perfeitamente nosso conceito de crescimento digital.",
    team: "Equipe Arfen",
    teamRole: "Branding Digital",
    image: "/logos/expansao-midia.webp",
    description: "Logo contemporâneo com tipografia 3D e aviões de papel em gradiente pastel suave amarelo-rosa-roxo.",
  },
  {
    slug: "ponto-juridico-logo",
    title: "Ponto Jurídico",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Ponto Jurídico Advocacia",
    rating: 5.0,
    testimonial: "Identidade premium que nos posicionou entre os escritórios mais respeitados da região.",
    team: "Equipe Arfen",
    teamRole: "Branding Jurídico Premium",
    image: "/logos/ponto-juridico.webp",
    description: "Logo luxuoso com Lady Justice dourada segurando balança e espada dentro de escudo heráldico em fundo azul marinho.",
  },
  {
    slug: "dimarzio-turismo-logo",
    title: "DiMarzio Turismo",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "DiMarzio Agência de Viagens",
    rating: 5.0,
    testimonial: "Logo que captura perfeitamente nossa essência de conectar pessoas aos destinos dos sonhos.",
    team: "Equipe Arfen",
    teamRole: "Branding Turismo",
    image: "/logos/dimarzio-turismo.webp",
    description: "Logo circular laranja com relógio e principais monumentos mundiais (Torre Eiffel, Big Ben, Estátua da Liberdade, Sagrada Família) sobre globo.",
  },
  {
    slug: "bookgrid-logo",
    title: "BookGrid",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "BookGrid Platform",
    rating: 5.0,
    testimonial: "Marca tech moderna que impulsionou nossa presença no mercado editorial digital.",
    team: "Equipe Arfen",
    teamRole: "Branding Tech/Editorial",
    image: "/logos/bookgrid.png",
    description: "Logo moderno com símbolo 3D geométrico dourado tipo play button e tipografia bicolor sobre fundo preto.",
  },
  {
    slug: "golden-dragon-logo",
    title: "Golden Dragon",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Marca Premium Asiática",
    rating: 5.0,
    testimonial: "Símbolo luxuoso que transmite força, tradição e exclusividade da nossa marca.",
    team: "Equipe Arfen",
    teamRole: "Branding Luxo & Ornamental",
    image: "/logos/golden-dragon.webp",
    description: "Dragão oriental dourado ornamental em forma de S com detalhes elaborados, asas e chamas sobre fundo branco.",
  },
  {
    slug: "abstract-tech-geo-logo",
    title: "Abstract Tech",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Tech Startup",
    rating: 5.0,
    testimonial: "Design minimalista e futurista que define perfeitamente nossa visão de inovação.",
    team: "Equipe Arfen",
    teamRole: "Branding Tech Minimalista",
    image: "/logos/abstract-tech-geo.png",
    description: "Logo geométrico abstrato com formas triangulares sobrepostas em gradiente azul criando envelope 3D sobre fundo escuro com glow.",
  },
  {
    slug: "carun-automotive-logo",
    title: "Carun Automotive",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Carun",
    rating: 5.0,
    testimonial: "Logo esportivo que transmite velocidade e potência, perfeito para nossa marca automotiva.",
    team: "Equipe Arfen",
    teamRole: "Branding Automotivo",
    image: "/logos/carun-automotive.jpeg",
    description: "Logo automotivo com superesportivo laranja sob arco estilizado e escudo, tipografia bold em gradiente laranja sobre fundo preto.",
  },
  {
    slug: "textium-logo",
    title: "Textium",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Textium",
    rating: 5.0,
    testimonial: "Marca moderna e impactante que nos posicionou como referência em inovação digital.",
    team: "Equipe Arfen",
    teamRole: "Branding 3D & Motion",
    image: "/logos/textium.png",
    description: "Logo moderno com fita 3D torcida em preto e verde neon formando letra S, tipografia bold TEXTIUM em verde sobre fundo claro.",
  },
  {
    slug: "os-foras-da-caixa-logo",
    title: "Os Foras da Caixa",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Os Foras da Caixa",
    rating: 5.0,
    testimonial: "Identidade vibrante que captura perfeitamente nosso espírito criativo e inovador.",
    team: "Equipe Arfen",
    teamRole: "Branding Criativo & Ilustração",
    image: "/logos/os-foras-da-caixa.jpg",
    description: "Logo ilustrativo colorido com pessoas saltando de uma caixa aberta, representando criatividade e pensamento fora da caixa.",
  },
  {
    slug: "cortes-milionarios-logo",
    title: "Cortes Milionários",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Cortes Milionários",
    rating: 5.0,
    testimonial: "Design impactante que transmite a essência premium do nosso conteúdo.",
    team: "Equipe Arfen",
    teamRole: "Branding Digital & Social Media",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/cortes-3bfGAez51OYFAd6bSLVTzUS02oLmUC.png",
    description: "Logo moderno com tipografia bold 'CORTES' em branco e 'MILIONÁRIOS' em verde neon estilizado sobre fundo preto.",
  },
  {
    slug: "circular-d-logo",
    title: "Logo D Circular",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Cliente D",
    rating: 5.0,
    testimonial: "Logo minimalista e elegante que representa perfeitamente nossa marca.",
    team: "Equipe Arfen",
    teamRole: "Branding Minimalista",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Design%20sem%20nome%20%2812%29-yvELXBzJIU68fauItAC9wrTzXAcV8d.png",
    description: "Logo circular minimalista com letra D estilizada em branco sobre fundo preto sólido.",
  },
  {
    slug: "daniel-almeida-vereador-logo",
    title: "Vereador Daniel Almeida",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Daniel Almeida 10010",
    rating: 5.0,
    testimonial: "Identidade política moderna que fortaleceu nossa comunicação e reconhecimento.",
    team: "Equipe Arfen",
    teamRole: "Branding Político",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Prachason%20Neue%20Mon%20Condensed-TE5SYc6Lb6xcL4JhGIEthrcNWDtqJx.png",
    description: "Logo político com 'Vereador' em azul, 'Daniel' em azul, 'Almeida' em amarelo e número '10010' em verde.",
  },
  {
    slug: "cabo-ademir-vereador-logo",
    title: "Vereador Cabo Ademir",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Cabo Ademir",
    rating: 5.0,
    testimonial: "Design forte e institucional que consolidou nossa imagem política.",
    team: "Equipe Arfen",
    teamRole: "Branding Político & Institucional",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Vespasiano-BZNHfK7K3UiBFjC2zqrv9A8JUWc5cX.png",
    description: "Logo político com escudo azul, 'CABO' em verde com chevrons, 'ADEMIR' em azul e 'Vereador' em cinza.",
  },
  {
    slug: "mebil-logo",
    title: "Mebil",
    category: "logos",
    categoryLabel: "Identidade Visual",
    client: "Mebil",
    rating: 5.0,
    testimonial: "Logo moderno e profissional que elevou nossa presença de marca.",
    team: "Equipe Arfen",
    teamRole: "Branding Corporativo",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Design%20sem%20nome%20%2811%29-8esnLwDkofv80UPYUGsJ0gurpp1Oy5.png",
    description: "Logo contemporâneo com 'm' em amarelo e 'ebil' em cinza escuro, tipografia clean e moderna.",
  },

  // Videos - Vimeo
  {
    slug: "video-vimeo-01",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Produção de vídeo profissional que superou todas as expectativas.",
    team: "Equipe Arfen",
    teamRole: "Produção & Edição",
    image: "/placeholder.svg?height=600&width=800",
    description: "Vídeo profissional com storytelling envolvente e produção de alta qualidade.",
    videoUrl: "https://player.vimeo.com/video/1049276275",
  },
  {
    slug: "video-vimeo-02",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Vídeo impactante que gerou resultados reais para nossa marca.",
    team: "Equipe Arfen",
    teamRole: "Direção & Edição",
    image: "/placeholder.svg?height=600&width=800",
    description: "Produção audiovisual completa com direção criativa e edição profissional.",
    videoUrl: "https://player.vimeo.com/video/1066763132",
  },
  {
    slug: "video-vimeo-03",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Qualidade cinematográfica que elevou a percepção da nossa empresa.",
    team: "Equipe Arfen",
    teamRole: "Cinematografia",
    image: "/placeholder.svg?height=600&width=800",
    description: "Vídeo cinematográfico com iluminação profissional e composição visual impecável.",
    videoUrl: "https://player.vimeo.com/video/1070845669",
  },
  {
    slug: "video-vimeo-04",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Conteúdo audiovisual que conectou profundamente com nosso público.",
    team: "Equipe Arfen",
    teamRole: "Produção Criativa",
    image: "/placeholder.svg?height=600&width=800",
    description: "Produção criativa com narrativa envolvente e técnicas de edição avançadas.",
    videoUrl: "https://player.vimeo.com/video/1051635211",
  },
  {
    slug: "video-vimeo-05",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Vídeo que traduziu perfeitamente a essência do nosso projeto.",
    team: "Equipe Arfen",
    teamRole: "Direção Criativa",
    image: "/placeholder.svg?height=600&width=800",
    description: "Direção criativa e produção audiovisual com foco em identidade de marca.",
    videoUrl: "https://player.vimeo.com/video/1068651674",
  },
  {
    slug: "video-vimeo-06",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Produção de altíssimo nível que posicionou nossa marca no mercado.",
    team: "Equipe Arfen",
    teamRole: "Produção Premium",
    image: "/placeholder.svg?height=600&width=800",
    description: "Vídeo premium com produção de alta qualidade e storytelling impactante.",
    videoUrl: "https://player.vimeo.com/video/1049265993",
  },
  {
    slug: "video-vimeo-07",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Resultado visual excepcional que superou nossas melhores expectativas.",
    team: "Equipe Arfen",
    teamRole: "Videografia Profissional",
    image: "/placeholder.svg?height=600&width=800",
    description: "Videografia profissional com equipamentos de ponta e edição refinada.",
    videoUrl: "https://player.vimeo.com/video/1049285477",
  },
  {
    slug: "video-vimeo-08",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Conteúdo audiovisual transformador que gerou grande engajamento.",
    team: "Equipe Arfen",
    teamRole: "Conteúdo Audiovisual",
    image: "/placeholder.svg?height=600&width=800",
    description: "Conteúdo audiovisual dinâmico otimizado para máximo engajamento.",
    videoUrl: "https://player.vimeo.com/video/1065650245",
  },
  {
    slug: "video-vimeo-09",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Vídeo institucional que comunicou nossos valores com excelência.",
    team: "Equipe Arfen",
    teamRole: "Vídeo Institucional",
    image: "/placeholder.svg?height=600&width=800",
    description: "Vídeo institucional com comunicação clara e produção de alto padrão.",
    videoUrl: "https://player.vimeo.com/video/1068653190",
  },
  // Videos - YouTube
  {
    slug: "video-youtube-01",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Produção profissional que destacou nosso conteúdo no YouTube.",
    team: "Equipe Arfen",
    teamRole: "Produção YouTube",
    image: "/placeholder.svg?height=600&width=800",
    description: "Produção audiovisual otimizada para plataformas digitais com alta qualidade.",
    videoUrl: "https://www.youtube.com/embed/7JXGkvbQrlQ",
  },
  {
    slug: "video-youtube-02",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Conteúdo em vídeo que impulsionou nosso canal e engajamento.",
    team: "Equipe Arfen",
    teamRole: "Conteúdo Digital",
    image: "/placeholder.svg?height=600&width=800",
    description: "Conteúdo em vídeo profissional para canais digitais e redes sociais.",
    videoUrl: "https://www.youtube.com/embed/riZdOEwtlWg",
  },
  {
    slug: "video-youtube-03",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Vídeo de alta qualidade que gerou milhares de visualizações orgânicas.",
    team: "Equipe Arfen",
    teamRole: "Produção de Conteúdo",
    image: "/placeholder.svg?height=600&width=800",
    description: "Vídeo com alto potencial de viralização e engajamento orgânico.",
    videoUrl: "https://www.youtube.com/embed/xFmQ2uDVP0g",
  },
  {
    slug: "video-youtube-04",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Resultado audiovisual que superou todas as métricas de performance.",
    team: "Equipe Arfen",
    teamRole: "Performance Audiovisual",
    image: "/placeholder.svg?height=600&width=800",
    description: "Produção de vídeo focada em performance e resultados mensuráveis.",
    videoUrl: "https://www.youtube.com/embed/a7HxhH1iXFQ",
  },
  {
    slug: "video-youtube-05",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Edição profissional que transformou nosso material bruto em arte.",
    team: "Equipe Arfen",
    teamRole: "Edição Profissional",
    image: "/placeholder.svg?height=600&width=800",
    description: "Edição profissional com cortes dinâmicos e pós-produção de alto nível.",
    videoUrl: "https://www.youtube.com/embed/It914UU3hzk",
  },
  {
    slug: "video-youtube-06",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Conteúdo audiovisual que definiu o novo padrão da nossa comunicação.",
    team: "Equipe Arfen",
    teamRole: "Comunicação Visual",
    image: "/placeholder.svg?height=600&width=800",
    description: "Comunicação audiovisual estratégica com foco em impacto e conversão.",
    videoUrl: "https://www.youtube.com/embed/vsAcwjO_M2M",
  },
  {
    slug: "video-shorts-01",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Short dinâmico que viralizou e trouxe milhares de novos seguidores.",
    team: "Equipe Arfen",
    teamRole: "Conteúdo Short-Form",
    image: "/placeholder.svg?height=600&width=800",
    description: "Conteúdo short-form otimizado para máximo engajamento e viralização.",
    videoUrl: "https://www.youtube.com/embed/GjBV4GxmWA0",
  },
  {
    slug: "video-shorts-02",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Produção vertical impactante que dominou o feed dos seguidores.",
    team: "Equipe Arfen",
    teamRole: "Produção Vertical",
    image: "/placeholder.svg?height=600&width=800",
    description: "Produção audiovisual vertical com ritmo acelerado e edição impactante.",
    videoUrl: "https://www.youtube.com/embed/c3ybMy9Wo10",
  },
  {
    slug: "video-shorts-03",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Conteúdo rápido e envolvente que gerou alto engajamento orgânico.",
    team: "Equipe Arfen",
    teamRole: "Conteúdo Rápido",
    image: "/placeholder.svg?height=600&width=800",
    description: "Vídeo curto com narrativa envolvente e transições criativas.",
    videoUrl: "https://www.youtube.com/embed/xaoPL1yaplA",
  },
  {
    slug: "video-shorts-04",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Short profissional que se destacou pela qualidade de produção.",
    team: "Equipe Arfen",
    teamRole: "Short-Form Premium",
    image: "/placeholder.svg?height=600&width=800",
    description: "Produção short-form premium com qualidade cinematográfica.",
    videoUrl: "https://www.youtube.com/embed/bFdSbmK-CJQ",
  },
  {
    slug: "video-shorts-05",
    title: "Produção Audiovisual",
    category: "videos",
    categoryLabel: "Produção Audiovisual",
    client: "Cliente Arfen",
    rating: 5.0,
    testimonial: "Conteúdo viral que alcançou milhares de visualizações em poucas horas.",
    team: "Equipe Arfen",
    teamRole: "Conteúdo Viral",
    image: "/placeholder.svg?height=600&width=800",
    description: "Vídeo viral com edição dinâmica e storytelling envolvente.",
    videoUrl: "https://www.youtube.com/embed/PK8AlvTGjO0",
  },

  // Sites
  {
    slug: "restart-ajuda-site",
    title: "Restart Ajuda",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "Restart Ajuda",
    rating: 5.0,
    testimonial: "Site que transformou nossa presenca digital e conectou milhares de pessoas em recuperacao.",
    team: "Equipe Arfen",
    teamRole: "Web Design & Dev",
    image: "/sites/restart-ajuda.png",
    description: "Landing page institucional dark com tipografia impactante ciano, CTA de conversao e video embed integrado.",
    siteUrl: "https://restart-ajuda.vercel.app",
  },
  {
    slug: "megaclick-landing-site",
    title: "MegaClick",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "MegaClick",
    rating: 5.0,
    testimonial: "Landing page SaaS que converteu 287% mais leads desde o lancamento.",
    team: "Equipe Arfen",
    teamRole: "SaaS Landing Page",
    image: "/sites/megaclick-landing.png",
    description: "Landing page SaaS dark-blue com metricas de resultados, cards de beneficios e CTA de conversao otimizado.",
    siteUrl: "https://www.megaclickboost.com",
  },
  {
    slug: "vida-financeira-landing-site",
    title: "Vida Financeira",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "Curso Financeiro",
    rating: 5.0,
    testimonial: "Pagina de vendas que gerou mais de 10.000 inscricoes para o curso online.",
    team: "Equipe Arfen",
    teamRole: "Sales Page Design",
    image: "/sites/vida-financeira-landing.png",
    description: "Pagina de vendas premium dark-gold com metodologia comprovada, video de apresentacao e prova social.",
    siteUrl: "https://www.metodocodigodariqueza.com",
  },
  {
    slug: "freebook-colecao-site",
    title: "FreeBook",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "Rud Gregorio",
    rating: 5.0,
    testimonial: "Plataforma de e-books que elevou as vendas digitais e posicionou a marca como referencia.",
    team: "Equipe Arfen",
    teamRole: "E-commerce Digital",
    image: "/sites/freebook-colecao.png",
    description: "Plataforma de livros digitais dark-gold com carrossel de colecoes, cards de produtos e design editorial premium.",
    siteUrl: "https://v0-bookgrid.vercel.app/",
  },
  {
    slug: "mega-clique-dashboard-site",
    title: "Mega Clique Dashboard",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "Mega Clique",
    rating: 5.0,
    testimonial: "Dashboard que revolucionou a gestao de marketplace com analises em tempo real.",
    team: "Equipe Arfen",
    teamRole: "Dashboard & App Web",
    image: "/sites/mega-clique-dashboard.png",
    description: "Dashboard SaaS dark com graficos de performance, KPIs coloridos, taxa de sucesso e analises diarias.",
    siteUrl: "https://megaclick.bolt.host/",
  },
  {
    slug: "textium-ebook-store-site",
    title: "Textium E-book Store",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "Textium",
    rating: 5.0,
    testimonial: "Loja digital que triplicou as vendas de e-books com design imersivo e moderno.",
    team: "Equipe Arfen",
    teamRole: "E-commerce & Design",
    image: "/sites/textium-ebook-store.png",
    description: "E-book store premium dark-green com glow neon, tipografia bold e navegacao intuitiva.",
  },
  {
    slug: "st-city-store-site",
    title: "ST City Store",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "ST City",
    rating: 5.0,
    testimonial: "E-commerce esportivo que se tornou referencia em vendas de camisas de futebol online.",
    team: "Equipe Arfen",
    teamRole: "E-commerce Esportivo",
    image: "/sites/st-city-store.png",
    description: "E-commerce dark-gold de camisas de futebol com banner hero dinamico, bandeira do Brasil e navegacao por categorias.",
    siteUrl: "https://streetcity.lojavirtualnuvem.com.br/?preview_theme_installation_id=6162882",
  },
  {
    slug: "svk-store-site",
    title: "SVK Store",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "SVK",
    rating: 5.0,
    testimonial: "Loja virtual que aumentou o faturamento em 200% com design clean e focado em conversao.",
    team: "Equipe Arfen",
    teamRole: "E-commerce Fashion",
    image: "/sites/svk-store.png",
    description: "E-commerce de moda masculina light-yellow com grid de produtos, precos com desconto e navegacao por categorias.",
    siteUrl: "https://prefixsyk2.lojavirtualnuvem.com.br/?exit_preview_theme_installation",
  },
  {
    slug: "bookgrid-library-site",
    title: "BookGrid Library",
    category: "sites",
    categoryLabel: "Desenvolvimento Web",
    client: "BookGrid",
    rating: 5.0,
    testimonial: "Plataforma de livros que transformou a experiencia de leitura digital dos nossos usuarios.",
    team: "Equipe Arfen",
    teamRole: "Plataforma Digital",
    image: "/sites/bookgrid-library.png",
    description: "Plataforma de livros digitais dark com fundo de estante, busca por titulo/autor, tags de categorias e CTA gold Explore Full Library.",
    siteUrl: "https://www.ebookgridstore.com",
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}

export function getProjectsByCategory(category: ProjectCategory): Project[] {
  return projects.filter((p) => p.category === category)
}
